### ISSUE TITLE
Move away from Heroku

### ISSUE THREAD

**Issue by madhead** [madhead/tyzenhaus#79]
https://blog.heroku.com/next-chapter

**Comment by madhead** [comment]
### [Fly.io](https://fly.io)

- [ ] Configure the application on fly.io (`flyctl`, `fly.toml`, etc).
- [ ] Configure a database
- [ ] Configure the deployment
- [ ] Configure TLS (HTTPS)
- [ ] Ensure the deployment is working
- [ ] Move the data
- [ ] Change the webhook
